### ISSUE TITLE
有按键显示的 Gif 图是用什么软件录的

### ISSUE THREAD

**Issue by PoBlue** [linesh-simplicity/eslint-config-udacity#1]
看到图里熟练的 Vim 手法😊

想问下那个有按键显示的 Gif 图是用什么软件录的？

**Comment by EthanLin-TWer** [comment]
这个其实是两个软件做的，有按键显示的那个叫 KeyCastr，可以通过 `brew cask` 直接安装；录屏的软件应该是用 OBS，我也记不太清楚啦，也可以通过 `brew cask` 直接安装使用。

```bash
brew cask install keycastr
brew cask install obs
```

**Comment by PoBlue** [comment]
哦，好的，谢谢推荐
